# Recent grads.csv

# Challenge

## Introduction to the datase

- Read all-ages.csv from a DataFrame and assign it to the all_ages variable.
- Read recent-grads.csv from a DataFrame and assign it to the recent_grads variable.
- Display the first 5 lines of all_ages and recent_grads.

In [1]:
import numpy as np
import pandas as pd
from pandas import Series
%matplotlib inline
import matplotlib.pyplot as plt
all_ages = pd.read_csv('all-ages.csv')
all_ages.head()

,Major_code,Major,Major_category,Total,Employed,Employed_full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th
0,1100,GENERAL AGRICULTURE,Agriculture & Natural Resources,128148.0,90245.0,74078.0,2423.0,0.026147,50000.0,34000.0,80000.0
1,1101,AGRICULTURE PRODUCTION AND MANAGEMENT,Agriculture & Natural Resources,95326.0,76865.0,64240.0,2266.0,0.028636,54000.0,36000.0,80000.0
2,1102,AGRICULTURAL ECONOMICS,Agriculture & Natural Resources,33955.0,26321.0,22810.0,821.0,0.030248,63000.0,40000.0,98000.0
3,1103,ANIMAL SCIENCES,Agriculture & Natural Resources,103549.0,81177.0,64937.0,3619.0,0.042679,46000.0,30000.0,72000.0
4,1104,FOOD SCIENCE,Agriculture & Natural Resources,24280.0,17281.0,12722.0,894.0,0.049188,62000.0,38500.0,90000.0

In [2]:
recent_grads = pd.read_csv('recent-grads.csv')
recent_grads.head()

,Rank,Major_code,Major,Major_category,Total,Sample_size,Men,Women,ShareWomen,Employed,...,Part_time,Full_time_year_round,Unemployed,Unemployment_rate,Median,P25th,P75th,College_jobs,Non_college_jobs,Low_wage_jobs
0,1,2419.0,PETROLEUM ENGINEERING,Engineering,2339.0,36.0,2057.0,282.0,0.120564,1976.0,...,270.0,1207.0,37.0,0.018381,110000.0,95000.0,125000.0,1534.0,364.0,193.0
1,2,2416.0,MINING AND MINERAL ENGINEERING,Engineering,756.0,7.0,679.0,77.0,0.101852,640.0,...,170.0,388.0,85.0,0.117241,75000.0,55000.0,90000.0,350.0,257.0,50.0
2,3,2415.0,METALLURGICAL ENGINEERING,Engineering,856.0,3.0,725.0,131.0,0.153037,648.0,...,133.0,340.0,16.0,0.024096,73000.0,50000.0,105000.0,456.0,176.0,0.0
3,4,2417.0,NAVAL ARCHITECTURE AND MARINE ENGINEERING,Engineering,1258.0,16.0,1123.0,135.0,0.107313,758.0,...,150.0,692.0,40.0,0.050125,70000.0,43000.0,80000.0,529.0,102.0,0.0
4,5,2405.0,CHEMICAL ENGINEERING,Engineering,32260.0,289.0,21239.0,11021.0,0.341631,25694.0,...,5180.0,16697.0,1672.0,0.061098,65000.0,50000.0,75000.0,18314.0,4440.0,972.0

## Number of students per Major category

- Return the unique values of Major_category.
>- Use the Series.unique() method to return the unique values of a Series.

In [3]:
all_ages["Major_category"].unique()

array(['Agriculture & Natural Resources', 'Biology & Life Science',
       'Engineering', 'Humanities & Liberal Arts',
       'Communications & Journalism', 'Computers & Mathematics',
       'Industrial Arts & Consumer Services', 'Education',
       'Law & Public Policy', 'Interdisciplinary', 'Health',
       'Social Science', 'Physical Sciences', nan,
       'Psychology & Social Work', 'Arts', 'Business'], dtype=object)

In [4]:
len(all_ages['Major_category'].unique().tolist())

17

In [5]:
recent_grads['Major_category'].unique()

array(['Engineering', 'Business', 'Physical Sciences',
       'Law & Public Policy', 'Computers & Mathematics',
       'Agriculture & Natural Resources',
       'Industrial Arts & Consumer Services', 'Arts', 'Health',
       'Social Science', nan, 'Biology & Life Science', 'Education',
       'Humanities & Liberal Arts', 'Psychology & Social Work',
       'Communications & Journalism', 'Interdisciplinary'], dtype=object)

In [6]:
len(recent_grads['Major_category'].unique().tolist())

17

In [7]:
Major_category_unique = all_ages['Major_category'].unique().tolist()
Major_category_unique

['Agriculture & Natural Resources',
 'Biology & Life Science',
 'Engineering',
 'Humanities & Liberal Arts',
 'Communications & Journalism',
 'Computers & Mathematics',
 'Industrial Arts & Consumer Services',
 'Education',
 'Law & Public Policy',
 'Interdisciplinary',
 'Health',
 'Social Science',
 'Physical Sciences',
 nan,
 'Psychology & Social Work',
 'Arts',
 'Business']

- For each unique value (use a for? loop):
>- Return all lines where Major_category is worth this unique value.
>- Calculate the total number of students representing this major category (Total column to sum).
>- You will store this result in the form of a dictionary containing a Major_category key and the number of students as a value.

In [8]:
recent = ['Major_category']
for Major_category in recent:
    print ('\n the total number of students representing this major category %s'%Major_category)
    print (recent_grads[Major_category].value_counts())
    newlist=(recent_grads[Major_category].value_counts())

 the total number of students representing this major category Major_category
Engineering                            29
Education                              16
Humanities & Liberal Arts              15
Biology & Life Science                 14
Business                               13
Health                                 12
Computers & Mathematics                11
Agriculture & Natural Resources        10
Physical Sciences                       9
Psychology & Social Work                9
Social Science                          9
Arts                                    8
Industrial Arts & Consumer Services     6
Law & Public Policy                     5
Communications & Journalism             4
Interdisciplinary                       1
Name: Major_category, dtype: int64

In [9]:
newdict = dict(newlist)
newdict

{'Engineering': 29,
 'Education': 16,
 'Humanities & Liberal Arts': 15,
 'Biology & Life Science': 14,
 'Business': 13,
 'Health': 12,
 'Computers & Mathematics': 11,
 'Agriculture & Natural Resources': 10,
 'Physical Sciences': 9,
 'Psychology & Social Work': 9,
 'Social Science': 9,
 'Arts': 8,
 'Industrial Arts & Consumer Services': 6,
 'Law & Public Policy': 5,
 'Communications & Journalism': 4,
 'Interdisciplinary': 1}

In [10]:

categorical_columns = ['Major_category']
#Print frequency of categories
for Major_category in categorical_columns:
    print ('\n the total number of students representing this major category %s'%Major_category)
    print (all_ages[Major_category].value_counts())
    allagelist=(all_ages[Major_category].value_counts())

 the total number of students representing this major category Major_category
Engineering                            29
Education                              16
Humanities & Liberal Arts              15
Biology & Life Science                 14
Business                               13
Health                                 12
Computers & Mathematics                11
Agriculture & Natural Resources        10
Physical Sciences                       9
Psychology & Social Work                9
Social Science                          9
Arts                                    8
Industrial Arts & Consumer Services     6
Law & Public Policy                     5
Communications & Journalism             4
Interdisciplinary                       1
Name: Major_category, dtype: int64

In [11]:
allagedict = dict(allagelist)
allagedict

{'Engineering': 29,
 'Education': 16,
 'Humanities & Liberal Arts': 15,
 'Biology & Life Science': 14,
 'Business': 13,
 'Health': 12,
 'Computers & Mathematics': 11,
 'Agriculture & Natural Resources': 10,
 'Physical Sciences': 9,
 'Psychology & Social Work': 9,
 'Social Science': 9,
 'Arts': 8,
 'Industrial Arts & Consumer Services': 6,
 'Law & Public Policy': 5,
 'Communications & Journalism': 4,
 'Interdisciplinary': 1}

#### Mission:
- Create a function in which you will use the Total column to calculate the number of students for each Major category (Major_category) in each dataset.
>- Store the result in 2 separate dictionaries.
>- The key for each dictionary will be Major_category and the value the total number of students.
>- For the dataset all_ages, store the result in a dictionary called aa_car_counts.
>- For the dataset recent_grads, store the result in a dictionary called rg_cat_counts.
- Other method: Use a table pivot.
- Display both dictionaries.

In [12]:
aa_car_counts=all_ages.set_index('Major_category').to_dict()
aa_car_counts

{'Major_code': {'Agriculture & Natural Resources': '1303',
  'Biology & Life Science': '4006',
  'Engineering': '5008',
  'Humanities & Liberal Arts': '6403',
  'Communications & Journalism': '1904',
  'Computers & Mathematics': '4005',
  'Industrial Arts & Consumer Services': '5901',
  'Education': '3501',
  'Law & Public Policy': '5402',
  'Interdisciplinary': '4000',
  'Health': '6199',
  'Social Science': '5599',
  'Physical Sciences': '5098',
  nan: '5701,"ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION",Industrial Arts & Consumer Services,15726,12607,10453,692,0.052033988,48000,32000,75000',
  'Psychology & Social Work': '5404',
  'Arts': '6099',
  'Business': '6299'},
 'Major': {'Agriculture & Natural Resources': 'NATURAL RESOURCES MANAGEMENT',
  'Biology & Life Science': 'COGNITIVE SCIENCE AND BIOPSYCHOLOGY',
  'Engineering': 'MATERIALS SCIENCE',
  'Humanities & Liberal Arts': 'UNITED STATES HISTORY',
  'Communications & Journalism': 'ADVERTISING AND PUBLIC RELATIONS',
  'Computers & Mathematics': 'MATHEMATICS AND COMPUTER SCIENCE',
  'Industrial Arts & Consumer Services': 'TRANSPORTATION SCIENCES AND TECHNOLOGIES',
  'Education': 'LIBRARY SCIENCE',
  'Law & Public Policy': 'PUBLIC POLICY',
  'Interdisciplinary': 'MULTI/INTERDISCIPLINARY STUDIES',
  'Health': 'MISCELLANEOUS HEALTH MEDICAL PROFESSIONS',
  'Social Science': 'MISCELLANEOUS SOCIAL SCIENCES',
  'Physical Sciences': 'MULTI-DISCIPLINARY OR GENERAL SCIENCE',
  nan: nan,
  'Psychology & Social Work': 'SOCIAL WORK',
  'Arts': 'MISCELLANEOUS FINE ARTS',
  'Business': 'MISCELLANEOUS BUSINESS & MEDICAL ADMINISTRATION'},
 'Total': {'Agriculture & Natural Resources': 83188.0,
  'Biology & Life Science': 6898.0,
  'Engineering': 7208.0,
  'Humanities & Liberal Arts': 17746.0,
  'Communications & Journalism': 186829.0,
  'Computers & Mathematics': 7184.0,
  'Industrial Arts & Consumer Services': 126639.0,
  'Education': 16193.0,
  'Law & Public Policy': 14782.0,
  'Interdisciplinary': 45199.0,
  'Health': 77647.0,
  'Social Science': 15882.0,
  'Physical Sciences': 427953.0,
  nan: nan,
  'Psychology & Social Work': 319163.0,
  'Arts': 8511.0,
  'Business': 102753.0},
 'Employed': {'Agriculture & Natural Resources': 65937.0,
  'Biology & Life Science': 5527.0,
  'Engineering': 5866.0,
  'Humanities & Liberal Arts': 11887.0,
  'Communications & Journalism': 147433.0,
  'Computers & Mathematics': 5874.0,
  'Industrial Arts & Consumer Services': 98814.0,
  'Education': 7091.0,
  'Law & Public Policy': 11147.0,
  'Interdisciplinary': 35706.0,
  'Health': 52610.0,
  'Social Science': 12307.0,
  'Physical Sciences': 308461.0,
  nan: nan,
  'Psychology & Social Work': 225081.0,
  'Arts': 6431.0,
  'Business': 77471.0},
 'Employed_full_time_year_round': {'Agriculture & Natural Resources': 50595.0,
  'Biology & Life Science': 3639.0,
  'Engineering': 4505.0,
  'Humanities & Liberal Arts': 8204.0,
  'Communications & Journalism': 111552.0,
  'Computers & Mathematics': 5039.0,
  'Industrial Arts & Consumer Services': 83519.0,
  'Education': 4330.0,
  'Law & Public Policy': 8196.0,
  'Interdisciplinary': 26038.0,
  'Health': 35676.0,
  'Social Science': 9444.0,
  'Physical Sciences': 238933.0,
  nan: nan,
  'Psychology & Social Work': 164020.0,
  'Arts': 3802.0,
  'Business': 61603.0},
 'Unemployed': {'Agriculture & Natural Resources': 3789.0,
  'Biology & Life Science': 284.0,
  'Engineering': 134.0,
  'Humanities & Liberal Arts': 943.0,
  'Communications & Journalism': 10624.0,
  'Computers & Mathematics': 150.0,
  'Industrial Arts & Consumer Services': 4902.0,
  'Education': 743.0,
  'Law & Public Policy': 959.0,
  'Interdisciplinary': 2990.0,
  'Health': 2978.0,
  'Social Science': 708.0,
  'Physical Sciences': 14613.0,
  nan: nan,
  'Psychology & Social Work': 14208.0,
  'Arts': 1190.0,
  'Business': 4308.0},
 'Unemployment_rate': {'Agriculture & Natural Resources': 0.054341279000000006,
  'Biology & Life Science': 0.048872827,
  'Engineering': 0.022333332999999997,
  'Humanities & Liberal Arts': 0.07349961,
  'Communications & Journalism': 0.067216257,
  'Computers & Mathematics': 0.024900397999999997,
  'Industrial Arts & Consumer Services': 0.047263682,
  'Education': 0.09484299199999999,
  'Law & Public Policy': 0.079216917,
  'Interdisciplinary': 0.077268968,
  'Health': 0.053572714,
  'Social Science': 0.054398771,
  'Physical Sciences': 0.045231124000000004,
  nan: nan,
  'Psychology & Social Work': 0.059375900999999995,
  'Arts': 0.156147487,
  'Business': 0.052678561},
 'Median': {'Agriculture & Natural Resources': 52000.0,
  'Biology & Life Science': 53000.0,
  'Engineering': 75000.0,
  'Humanities & Liberal Arts': 50000.0,
  'Communications & Journalism': 50000.0,
  'Computers & Mathematics': 92000.0,
  'Industrial Arts & Consumer Services': 67000.0,
  'Education': 40000.0,
  'Law & Public Policy': 60000.0,
  'Interdisciplinary': 43000.0,
  'Health': 45000.0,
  'Social Science': 52000.0,
  'Physical Sciences': 56000.0,
  nan: nan,
  'Psychology & Social Work': 40000.0,
  'Arts': 45000.0,
  'Business': 53000.0},
 'P25th': {'Agriculture & Natural Resources': 37100.0,
  'Biology & Life Science': 31500.0,
  'Engineering': 60000.0,
  'Humanities & Liberal Arts': 39000.0,
  'Communications & Journalism': 34000.0,
  'Computers & Mathematics': 53000.0,
  'Industrial Arts & Consumer Services': 42500.0,
  'Education': 30000.0,
  'Law & Public Policy': 38000.0,
  'Interdisciplinary': 32000.0,
  'Health': 32000.0,
  'Social Science': 40000.0,
  'Physical Sciences': 38000.0,
  nan: nan,
  'Psychology & Social Work': 30000.0,
  'Arts': 30000.0,
  'Business': 36000.0},
 'P75th': {'Agriculture & Natural Resources': 75000.0,
  'Biology & Life Science': 93000.0,
  'Engineering': 100000.0,
  'Humanities & Liberal Arts': 81000.0,
  'Communications & Journalism': 75000.0,
  'Computers & Mathematics': 136000.0,
  'Industrial Arts & Consumer Services': 98000.0,
  'Education': 55000.0,
  'Law & Public Policy': 90000.0,
  'Interdisciplinary': 55000.0,
  'Health': 62000.0,
  'Social Science': 80000.0,
  'Physical Sciences': 85000.0,
  nan: nan,
  'Psychology & Social Work': 53000.0,
  'Arts': 60000.0,
  'Business': 83000.0}}

In [13]:
rg_cat_counts=recent_grads.set_index('Major_category').to_dict()
rg_cat_counts

{'Rank': {'Engineering': '67',
  'Business': '128',
  'Physical Sciences': '111',
  'Law & Public Policy': '95',
  'Computers & Mathematics': '106',
  'Agriculture & Natural Resources': '162',
  'Industrial Arts & Consumer Services': '161',
  'Arts': '167',
  'Health': '164',
  'Social Science': '143',
  nan: '76,5701,"ELECTRICAL, MECHANICAL, AND PRECISION TECHNOLOGIES AND PRODUCTION",Industrial Arts & Consumer Services,2435,37,1869,566,0.232443532,2107,2057,287,1752,64,0.029479503,38400,22500,45000,221,1659,81',
  'Biology & Life Science': '169',
  'Education': '173',
  'Humanities & Liberal Arts': '168',
  'Psychology & Social Work': '172',
  'Communications & Journalism': '126',
  'Interdisciplinary': '110'},
 'Major_code': {'Engineering': 2504.0,
  'Business': 6211.0,
  'Physical Sciences': 5002.0,
  'Law & Public Policy': 5301.0,
  'Computers & Mathematics': 2001.0,
  'Agriculture & Natural Resources': 1199.0,
  'Industrial Arts & Consumer Services': 2201.0,
  'Arts': 6001.0,
  'Health': 6102.0,
  'Social Science': 5500.0,
  nan: nan,
  'Biology & Life Science': 3609.0,
  'Education': 3501.0,
  'Humanities & Liberal Arts': 3302.0,
  'Psychology & Social Work': 5203.0,
  'Communications & Journalism': 1903.0,
  'Interdisciplinary': 4000.0},
 'Major': {'Engineering': 'MECHANICAL ENGINEERING RELATED TECHNOLOGIES',
  'Business': 'HOSPITALITY MANAGEMENT',
  'Physical Sciences': 'ATMOSPHERIC SCIENCES AND METEOROLOGY',
  'Law & Public Policy': 'CRIMINAL JUSTICE AND FIRE PROTECTION',
  'Computers & Mathematics': 'COMMUNICATION TECHNOLOGIES',
  'Agriculture & Natural Resources': 'MISCELLANEOUS AGRICULTURE',
  'Industrial Arts & Consumer Services': 'COSMETOLOGY SERVICES AND CULINARY ARTS',
  'Arts': 'DRAMA AND THEATER ARTS',
  'Health': 'COMMUNICATION DISORDERS SCIENCES AND SERVICES',
  'Social Science': 'GENERAL SOCIAL SCIENCES',
  nan: nan,
  'Biology & Life Science': 'ZOOLOGY',
  'Education': 'LIBRARY SCIENCE',
  'Humanities & Liberal Arts': 'COMPOSITION AND RHETORIC',
  'Psychology & Social Work': 'COUNSELING PSYCHOLOGY',
  'Communications & Journalism': 'MASS MEDIA',
  'Interdisciplinary': 'MULTI/INTERDISCIPLINARY STUDIES'},
 'Total': {'Engineering': 4790.0,
  'Business': 43647.0,
  'Physical Sciences': 4043.0,
  'Law & Public Policy': 152824.0,
  'Computers & Mathematics': 18035.0,
  'Agriculture & Natural Resources': 1488.0,
  'Industrial Arts & Consumer Services': 10510.0,
  'Arts': 43249.0,
  'Health': 38279.0,
  'Social Science': 12920.0,
  nan: nan,
  'Biology & Life Science': 8409.0,
  'Education': 1098.0,
  'Humanities & Liberal Arts': 18953.0,
  'Psychology & Social Work': 4626.0,
  'Communications & Journalism': 52824.0,
  'Interdisciplinary': 12296.0},
 'Sample_size': {'Engineering': 71.0,
  'Business': 546.0,
  'Physical Sciences': 32.0,
  'Law & Public Policy': 1728.0,
  'Computers & Mathematics': 208.0,
  'Agriculture & Natural Resources': 24.0,
  'Industrial Arts & Consumer Services': 117.0,
  'Arts': 357.0,
  'Health': 95.0,
  'Social Science': 113.0,
  nan: nan,
  'Biology & Life Science': 47.0,
  'Education': 2.0,
  'Humanities & Liberal Arts': 151.0,
  'Psychology & Social Work': 21.0,
  'Communications & Journalism': 590.0,
  'Interdisciplinary': 128.0},
 'Men': {'Engineering': 894.0,
  'Business': 4416.0,
  'Physical Sciences': 13257.0,
  'Law & Public Policy': 3156.0,
  'Computers & Mathematics': 2563.0,
  'Agriculture & Natural Resources': 4754.0,
  'Industrial Arts & Consumer Services': 18616.0,
  'Arts': 7022.0,
  'Health': 11376.0,
  'Social Science': 62181.0,
  nan: nan,
  'Biology & Life Science': 3050.0,
  'Education': 134.0,
  'Humanities & Liberal Arts': 14440.0,
  'Psychology & Social Work': 931.0,
  'Communications & Journalism': 3741.0,
  'Interdisciplinary': 10031.0},
 'Women': {'Engineering': 542.0,
  'Business': 12185.0,
  'Physical Sciences': 1893.0,
  'Law & Public Policy': 451.0,
  'Computers & Mathematics': 16346.0,
  'Agriculture & Natural Resources': 12223.0,
  'Industrial Arts & Consumer Services': 11591.0,
  'Arts': 11931.0,
  'Health': 27468.0,
  'Social Science': 62893.0,
  nan: nan,
  'Biology & Life Science': 5359.0,
  'Education': 964.0,
  'Humanities & Liberal Arts': 28809.0,
  'Psychology & Social Work': 3695.0,
  'Communications & Journalism': 26730.0,
  'Interdisciplinary': 9848.0},
 'ShareWomen': {'Engineering': 0.377437326,
  'Business': 0.733991928,
  'Physical Sciences': 0.124950495,
  'Law & Public Policy': 0.125034655,
  'Computers & Mathematics': 0.8644560790000001,
  'Agriculture & Natural Resources': 0.719974083,
  'Industrial Arts & Consumer Services': 0.38371900600000003,
  'Arts': 0.629504564,
  'Health': 0.7071362370000001,
  'Social Science': 0.502846315,
  nan: nan,
  'Biology & Life Science': 0.637293376,
  'Education': 0.877959927,
  'Humanities & Liberal Arts': 0.666119448,
  'Psychology & Social Work': 0.798746217,
  'Communications & Journalism': 0.8772275279999999,
  'Interdisciplinary': 0.495397153},
 'Employed': {'Engineering': 4186.0,
  'Business': 36728.0,
  'Physical Sciences': 3431.0,
  'Law & Public Policy': 125393.0,
  'Computers & Mathematics': 14779.0,
  'Agriculture & Natural Resources': 1290.0,
  'Industrial Arts & Consumer Services': 8650.0,
  'Arts': 36165.0,
  'Health': 29763.0,
  'Social Science': 9602.0,
  nan: nan,
  'Biology & Life Science': 6259.0,
  'Education': 742.0,
  'Humanities & Liberal Arts': 15053.0,
  'Psychology & Social Work': 3777.0,
  'Communications & Journalism': 44679.0,
  'Interdisciplinary': 9821.0},
 'Full_time': {'Engineering': 4175.0,
  'Business': 32160.0,
  'Physical Sciences': 2659.0,
  'Law & Public Policy': 109970.0,
  'Computers & Mathematics': 11981.0,
  'Agriculture & Natural Resources': 1098.0,
  'Industrial Arts & Consumer Services': 7662.0,
  'Arts': 25147.0,
  'Health': 19975.0,
  'Social Science': 7700.0,
  nan: nan,
  'Biology & Life Science': 5043.0,
  'Education': 593.0,
  'Humanities & Liberal Arts': 10121.0,
  'Psychology & Social Work': 3154.0,
  'Communications & Journalism': 35769.0,
  'Interdisciplinary': 8032.0},
 'Part_time': {'Engineering': 247.0,
  'Business': 7494.0,
  'Physical Sciences': 1309.0,
  'Law & Public Policy': 32242.0,
  'Computers & Mathematics': 4690.0,
  'Agriculture & Natural Resources': 335.0,
  'Industrial Arts & Consumer Services': 2064.0,
  'Arts': 15994.0,
  'Health': 13862.0,
  'Social Science': 3396.0,
  nan: nan,
  'Biology & Life Science': 2190.0,
  'Education': 237.0,
  'Humanities & Liberal Arts': 6612.0,
  'Psychology & Social Work': 965.0,
  'Communications & Journalism': 13078.0,
  'Interdisciplinary': 3173.0},
 'Full_time_year_round': {'Engineering': 3607.0,
  'Business': 23106.0,
  'Physical Sciences': 2161.0,
  'Law & Public Policy': 88548.0,
  'Computers & Mathematics': 9085.0,
  'Agriculture & Natural Resources': 936.0,
  'Industrial Arts & Consumer Services': 5949.0,
  'Arts': 16891.0,
  'Health': 14460.0,
  'Social Science': 5679.0,
  nan: nan,
  'Biology & Life Science': 3602.0,
  'Education': 410.0,
  'Humanities & Liberal Arts': 7832.0,
  'Psychology & Social Work': 2738.0,
  'Communications & Journalism': 27521.0,
  'Interdisciplinary': 6234.0},
 'Unemployed': {'Engineering': 250.0,
  'Business': 2393.0,
  'Physical Sciences': 78.0,
  'Law & Public Policy': 11268.0,
  'Computers & Mathematics': 2006.0,
  'Agriculture & Natural Resources': 82.0,
  'Industrial Arts & Consumer Services': 510.0,
  'Arts': 3040.0,
  'Health': 1487.0,
  'Social Science': 1108.0,
  nan: nan,
  'Biology & Life Science': 304.0,
  'Education': 87.0,
  'Humanities & Liberal Arts': 1340.0,
  'Psychology & Social Work': 214.0,
  'Communications & Journalism': 4410.0,
  'Interdisciplinary': 749.0},
 'Unemployment_rate': {'Engineering': 0.056357078,
  'Business': 0.061169193,
  'Physical Sciences': 0.022228555,
  'Law & Public Policy': 0.082452199,
  'Computers & Mathematics': 0.11951146900000001,
  'Agriculture & Natural Resources': 0.05976676400000001,
  'Industrial Arts & Consumer Services': 0.055676856,
  'Arts': 0.07754113,
  'Health': 0.047583999999999994,
  'Social Science': 0.103454715,
  nan: nan,
  'Biology & Life Science': 0.04632028,
  'Education': 0.10494571800000001,
  'Humanities & Liberal Arts': 0.081742207,
  'Psychology & Social Work': 0.053620645999999994,
  'Communications & Journalism': 0.089836827,
  'Interdisciplinary': 0.070860927},
 'Median': {'Engineering': 40000.0,
  'Business': 33000.0,
  'Physical Sciences': 35000.0,
  'Law & Public Policy': 35000.0,
  'Computers & Mathematics': 35000.0,
  'Agriculture & Natural Resources': 29000.0,
  'Industrial Arts & Consumer Services': 29000.0,
  'Arts': 27000.0,
  'Health': 28000.0,
  'Social Science': 32000.0,
  nan: nan,
  'Biology & Life Science': 26000.0,
  'Education': 22000.0,
  'Humanities & Liberal Arts': 27000.0,
  'Psychology & Social Work': 23400.0,
  'Communications & Journalism': 33000.0,
  'Interdisciplinary': 35000.0},
 'P25th': {'Engineering': 27000.0,
  'Business': 25000.0,
  'Physical Sciences': 28000.0,
  'Law & Public Policy': 26000.0,
  'Computers & Mathematics': 25000.0,
  'Agriculture & Natural Resources': 23000.0,
  'Industrial Arts & Consumer Services': 20000.0,
  'Arts': 19200.0,
  'Health': 20000.0,
  'Social Science': 27000.0,
  nan: nan,
  'Biology & Life Science': 20000.0,
  'Education': 20000.0,
  'Humanities & Liberal Arts': 20000.0,
  'Psychology & Social Work': 19200.0,
  'Communications & Journalism': 25000.0,
  'Interdisciplinary': 25000.0},
 'P75th': {'Engineering': 52000.0,
  'Business': 42000.0,
  'Physical Sciences': 50000.0,
  'Law & Public Policy': 45000.0,
  'Computers & Mathematics': 45000.0,
  'Agriculture & Natural Resources': 42100.0,
  'Industrial Arts & Consumer Services': 36000.0,
  'Arts': 35000.0,
  'Health': 40000.0,
  'Social Science': 50000.0,
  nan: nan,
  'Biology & Life Science': 39000.0,
  'Education': 22000.0,
  'Humanities & Liberal Arts': 35000.0,
  'Psychology & Social Work': 26000.0,
  'Communications & Journalism': 45000.0,
  'Interdisciplinary': 44000.0},
 'College_jobs': {'Engineering': 1861.0,
  'Business': 2325.0,
  'Physical Sciences': 1808.0,
  'Law & Public Policy': 24348.0,
  'Computers & Mathematics': 4545.0,
  'Agriculture & Natural Resources': 483.0,
  'Industrial Arts & Consumer Services': 563.0,
  'Arts': 6994.0,
  'Health': 19957.0,
  'Social Science': 3602.0,
  nan: nan,
  'Biology & Life Science': 2771.0,
  'Education': 288.0,
  'Humanities & Liberal Arts': 4855.0,
  'Psychology & Social Work': 2403.0,
  'Communications & Journalism': 12855.0,
  'Interdisciplinary': 5176.0},
 'Non_college_jobs': {'Engineering': 2121.0,
  'Business': 23341.0,
  'Physical Sciences': 1317.0,
  'Law & Public Policy': 88858.0,
  'Computers & Mathematics': 8794.0,
  'Agriculture & Natural Resources': 626.0,
  'Industrial Arts & Consumer Services': 7384.0,
  'Arts': 25313.0,
  'Health': 9404.0,
  'Social Science': 4778.0,
  nan: nan,
  'Biology & Life Science': 2947.0,
  'Education': 338.0,
  'Humanities & Liberal Arts': 8100.0,
  'Psychology & Social Work': 1245.0,
  'Communications & Journalism': 25297.0,
  'Interdisciplinary': 3903.0},
 'Low_wage_jobs': {'Engineering': 406.0,
  'Business': 9063.0,
  'Physical Sciences': 237.0,
  'Law & Public Policy': 18404.0,
  'Computers & Mathematics': 2495.0,
  'Agriculture & Natural Resources': 31.0,
  'Industrial Arts & Consumer Services': 3163.0,
  'Arts': 11068.0,
  'Health': 5125.0,
  'Social Science': 1634.0,
  nan: nan,
  'Biology & Life Science': 743.0,
  'Education': 192.0,
  'Humanities & Liberal Arts': 3466.0,
  'Psychology & Social Work': 308.0,
  'Communications & Journalism': 6429.0,
  'Interdisciplinary': 1061.0}}

## Low-wage job rate

- Use the columns "Low_wage_jobs" and "Total" to calculate the proportion of young graduates who had to find low-wage jobs (recent_grads).
>- Remember that you can use the Series.sum() method to return the sum of the values of a column
- Store the result in the variable low_wage_proportion and display it.

In [14]:
low_wage_proportion = Series.sum((recent_grads[[ "Low_wage_jobs","Total"]])) 
low_wage_proportion

Low_wage_jobs     667405.0
Total            6771464.0
dtype: float64

## Compare datasets

- Use a for loop to browse all majors.
>- For each major and each DataFrame, filter only the lines of the DataFrame corresponding to that major.
>- Compare the values for the "Unemployment_rate" column to see which of the 2 DataFrames has the lowest value.
>- Increment (cad add 1) to the rg_lower_count variable if the value for Unemployment_rate is smaller in dataframe recent_grads than in dataframe all_ages
- Display the result rg_lower_count.

In [15]:
rg_lower_count=0
for i, row in all_ages.iterrows():
    for i1, row1 in recent_grads.iterrows():
        if row["Major"]==row1["Major"]:
            if row["Unemployment_rate"]>row1["Unemployment_rate"]:
                rg_lower_count=rg_lower_count+1
            break
   # print(row["Major"],row["Unemployment_rate"])
    
print(rg_lower_count)

42